version: "3"

services:
  web:
    build:
      context: .
    env_file: .env.docker-compose
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - bundle:/app/vendor/bundle
      - node_modules:/app/node_modules
    depends_on:
      - db
    tty: true
    stdin_open: true
  db:
    image: postgres:14
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /var/lib/postgresql/data/pgdata
    restart: always
    volumes:
      - pgdata:/var/lib/postgresql/data
  redis:
    image: redis
    restart: always
volumes:
  pgdata:
  bundle:
  node_modules:
